# Velikost grafů
# Spočtěte trojice v každém grafu a seřaďte výsledky sestupně dle velikosti. 

SELECT ?graph (COUNT(*) AS ?size)
WHERE {
  GRAPH ?graph {
    [] ?p [] .
  }
}
GROUP BY ?graph
ORDER BY DESC(?size)
