PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?concept ?broader
WHERE {
  {
    SELECT ?concept
    WHERE {
      ?concept a skos:Concept .
    }
  }
  ?concept skos:broader ?broader .
}
