PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?concept
WHERE {
  ?concept rdf:type skos:Concept .
  OPTIONAL {
    ?concept skos:broader ?broader .
  }
  # Some multi-byte characters to spice things up: řádně!
  FILTER BOUND(?broader)
}
